# NUMPY

* grande quantidade de dados
* se assemelha a lista mas tem mais "poder"
* numpy é escrito em C

In [1]:
#https://medium.com/ensina-ai/entendendo-a-biblioteca-numpy-4858fde63355

### O NumPy é uma poderosa biblioteca Python que é usada principalmente para realizar cálculos em Arrays Multidimensionais. O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como

## Modelos de Machine Learning
## Processamento de Imagem e Computação Gráfica
## Tarefas matemáticas

** Instalar a biblioteca caso não tennha
** py -m pip install numpy

In [2]:
import numpy as np

In [16]:
v  = [1111,22222,33333,44444]

In [4]:
type(v)

list

In [17]:
arr = np.array(v)

In [6]:
type(arr)

numpy.ndarray

In [7]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 '_distributor_init',
 '_globals',
 '_import_tools',
 '_mat',
 '_numpy_te

In [11]:
arr[1:3]

array([2, 3])

In [12]:
arr

array([1, 2, 3, 4])

In [18]:
print(arr)

[ 1111 22222 33333 44444]


In [14]:
print(v)

[1, 2, 3, 4]


In [19]:
for i in arr:
    print(i)

1111
22222
33333
44444


In [21]:
for i,j in enumerate(arr):
    print('indice %d' %(i))
    print('valor %d' %(j))
    print('-' * 30)

indice 0
valor 1111
------------------------------
indice 1
valor 22222
------------------------------
indice 2
valor 33333
------------------------------
indice 3
valor 44444
------------------------------


In [22]:
lista_lista = [[1,2,3],[4,5,6],[7,8,9]]

In [23]:
lista_lista

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
m_numpy = np.array(lista_lista)

In [25]:
m_numpy[0][0]

1

In [26]:
m_numpy[1][1]

5

In [27]:
m_numpy[1]

array([4, 5, 6])

In [31]:
m_numpy[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
v = list(range(10))

In [33]:
v

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [34]:
arr = np.arange(10)

In [35]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange(13,27)

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [ ]:
#como ver a ordem da matriz(linha,coluna)

In [39]:
arr.shape

(10L,)

In [42]:
m_numpy.shape

(3L, 3L)

In [43]:
#passar uma tupla como argumento
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
arr_3  = np.zeros((3,3,3))

In [45]:
arr_3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
arr_4 = np.zeros((1,2,3,4,5))

In [48]:
arr_4

array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]])

In [49]:
arr_3.shape

(3L, 3L, 3L)

In [50]:
arr_x = np.zeros((2,3,4))

In [51]:
arr_x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [52]:
arr = np.zeros((2,3,4,5,6,7))

In [53]:
arr

array([[[[[[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ...,

In [54]:
np.ones(3)

array([1., 1., 1.])

In [55]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [56]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
#setando valores em uma matriz já criada

In [57]:
arr = np.eye(3)

In [58]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
arr[0][2] = 3

In [60]:
arr

array([[1., 0., 3.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
arr[2][1] = 5

In [62]:
arr

array([[1., 0., 3.],
       [0., 1., 0.],
       [0., 5., 1.]])

In [63]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
#mudando a ordem da matriz

In [64]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [68]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [66]:
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a = [1]

In [ ]:
b = a.copy()

In [ ]:
b[0] = b[0] + 1

In [ ]:
a

In [ ]:
b

In [70]:
help(np.transpose)

Help on function transpose in module numpy.core.fromnumeric:

transpose(a, axes=None)
    Permute the dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : list of ints, optional
        By default, reverse the dimensions, otherwise permute the axes
        according to the values given.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    moveaxis
    argsort
    
    Notes
    -----
    Use `transpose(a, argsort(axes))` to invert the transposition of tensors
    when using the `axes` keyword argument.
    
    Transposing a 1-D array returns an unchanged view of the original array.
    
    Examples
    --------
    >>> x = np.arange(4).reshape((2,2))
    >>> x
    array([[0, 1],
           [2, 3]])
    
    >>> np.transpose(x)
    array([[0, 2],
           [1, 3]])
    
    >>> x = np.ones((1, 2, 3))
    >>> np.transpos

In [84]:
def test(v):
    for i,j in enumerate(v):
        v[i] = v[i] * 1000

In [85]:
x = [1,2,3,4,5]

In [90]:
dir(x)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setslice__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [87]:
x

[1, 2, 3, 4, 5]

In [75]:
arr = np.arange(5)

In [76]:
arr2 = arr.copy()

In [77]:
arr2[0] = 112391829

In [78]:
arr2

array([112391829,         1,         2,         3,         4])

In [79]:
arr

array([0, 1, 2, 3, 4])

In [94]:
arr = np.arange(20).reshape(5,4)

In [95]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [96]:
arr[1:3,2:4]

array([[ 6,  7],
       [10, 11]])

In [98]:
arr[3:,0:3]

array([[12, 13, 14],
       [16, 17, 18]])

In [99]:
arr[:,0]

array([ 0,  4,  8, 12, 16])

In [100]:
arr[3:,2:]

array([[14, 15],
       [18, 19]])

In [101]:
arr[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [102]:
v = [1,2,3,4]

In [103]:
2 in v

True

In [104]:
5 in v

False

In [109]:
9999 in arr

False

In [110]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [111]:
arr2 = np.arange(9).reshape(3,3)

In [112]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [113]:
9 in arr

True

In [114]:
34 in arr

False

In [115]:
arr = np.arange(4)

In [116]:
arr

array([0, 1, 2, 3])

In [124]:
arr[1:3] = arr[1:3] + 4

In [125]:
arr

array([0, 5, 6, 3])

In [128]:
arr2[2] = arr2[2] + 1000

In [129]:
arr2

array([[   0,    1,    2],
       [   3,    4,    5],
       [1006, 1007, 1008]])

In [119]:
arr2 + 4

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [120]:
arr - 10

array([-10,  -9,  -8,  -7])

In [121]:
arr2 - 10

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [132]:
[0,1,2,3] * 2

[0, 1, 2, 3, 0, 1, 2, 3]

In [133]:
arr * 2

array([ 0, 10, 12,  6])

In [134]:
arr2 * 2

array([[   0,    2,    4],
       [   6,    8,   10],
       [2012, 2014, 2016]])

In [135]:
arr / 2

array([0, 2, 3, 1])

In [136]:
arr2 / 2

array([[  0,   0,   1],
       [  1,   2,   2],
       [503, 503, 504]])

In [137]:
arr / 0

C:\Users\Bruno.Miura\AppData\Local\Continuum\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([0, 0, 0, 0])

In [138]:
arr2 / 0

C:\Users\Bruno.Miura\AppData\Local\Continuum\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in divide
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [139]:
np.sqrt(arr)

array([0.        , 2.23606798, 2.44948974, 1.73205081])

In [140]:
np.sqrt(arr2)

array([[ 0.        ,  1.        ,  1.41421356],
       [ 1.73205081,  2.        ,  2.23606798],
       [31.71750305, 31.73326331, 31.74901573]])

In [141]:
arr

array([0, 5, 6, 3])

In [142]:
arr2

array([[   0,    1,    2],
       [   3,    4,    5],
       [1006, 1007, 1008]])

In [143]:
np.sum(arr)

14

In [144]:
np.sum(arr2)

3036

In [145]:
arr.sum()

14

In [146]:
arr2.sum()

3036

In [147]:
np.mean(arr)

3.5

In [148]:
np.mean(arr2)

337.3333333333333

In [149]:
np.std(arr)

2.29128784747792

In [150]:
np.std(arr2)

473.52812893099485

In [ ]:
#operações com linha e coluna

In [151]:
arr2

array([[   0,    1,    2],
       [   3,    4,    5],
       [1006, 1007, 1008]])

In [152]:
#axis = 0 soma das colunas
arr2.sum(axis=0)

array([1009, 1012, 1015])

In [153]:
arr2.sum(axis=1)

array([   3,   12, 3021])

In [154]:
arr2.mean(axis=1)

array([1.000e+00, 4.000e+00, 1.007e+03])

In [155]:
arr2.mean(axis=0)

array([336.33333333, 337.33333333, 338.33333333])